name: sync1

 # on: 
 #   workflow_dispatch:手动运行
on: 
  schedule:
    - cron: '0 */3 * * *' # 每5分钟运行


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run script
      run: python .github/workflows/sync1.py
    - name: Commit and push if it changed
      run: |
        git config --global user.name 'lieying8'
        git config --global user.email 'qq504971271@gmail.com'
        git add .github/workflows/vvv.txt
        git diff --quiet && git diff --staged --quiet || git commit -m 'Updated data'
        git push

